using Microsoft.EntityFrameworkCore;
using HospitalSystem.Domain.Entities;
using HospitalSystem.Domain.Entities.Enums;
using Npgsql.EntityFrameworkCore.PostgreSQL;

namespace HospitalSystem.Infrastructure.Data
{
    public class ApplicationDbContext : DbContext
    {
        public ApplicationDbContext(DbContextOptions<ApplicationDbContext> options)
            : base(options) { }

        // Users & Profiles
        public DbSet<User> Users { get; set; } = null!;
        public DbSet<SpecialtyCategory> SpecialtyCategories { get; set; } = null!;
        public DbSet<Specialty> Specialties { get; set; } = null!;
        public DbSet<ProviderProfile> ProviderProfiles { get; set; } = null!;
        public DbSet<WorkSchedule> WorkSchedules { get; set; } = null!;
        public DbSet<PatientProfile> PatientProfiles { get; set; } = null!;

        // Clinic
        public DbSet<Clinic> Clinics { get; set; } = null!;
        public DbSet<ClinicWorkHours> ClinicWorkHours { get; set; } = null!;
        public DbSet<ClinicAddress> ClinicAddresses { get; set; } = null!;

        // Services
        public DbSet<ServiceCategory> ServiceCategories { get; set; } = null!;
        public DbSet<Service> Services { get; set; } = null!;
        public DbSet<Insurance> Insurances { get; set; } = null!;
        public DbSet<PatientInsurance> PatientInsurances { get; set; } = null!;
        public DbSet<ClinicInsurance> ClinicInsurances { get; set; } = null!;
        public DbSet<ClinicService> ClinicServices { get; set; } = null!;

        // Requests
        public DbSet<ServiceRequest> ServiceRequests { get; set; } = null!;
        public DbSet<ServiceResult> ServiceResults { get; set; } = null!;
        public DbSet<Payment> Payments { get; set; } = null!;

        // Notifications & Logs
        public DbSet<Notification> Notifications { get; set; } = null!;
        public DbSet<AuditLog> AuditLogs { get; set; } = null!;

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            // Note: Table and column names will be auto-generated by EF Core
            // All enums use HasConversion<string>() to store as VARCHAR in PostgreSQL
            // PostgreSQL custom ENUM types have been removed for better compatibility

            // User Configuration
            modelBuilder.Entity<User>(entity =>
            {
                entity.ToTable("User");
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.FirstName).HasMaxLength(255);
                entity.Property(e => e.LastName).HasMaxLength(255);
                entity.Property(e => e.NationalCode).HasMaxLength(10);
                entity.Property(e => e.Phone).HasMaxLength(20);
                entity.Property(e => e.PasswordHash).HasMaxLength(255);
                entity.Property(e => e.AvatarUrl).HasMaxLength(255);
                entity.Property(e => e.IsActive).HasDefaultValue(true);
                entity.Property(e => e.CreatedAt)
                    .HasDefaultValueSql("NOW()")
                    .HasConversion(
                        v => v.Kind == DateTimeKind.Unspecified ? DateTime.SpecifyKind(v, DateTimeKind.Utc) : v.ToUniversalTime(),
                        v => DateTime.SpecifyKind(v, DateTimeKind.Utc));
                entity.Property(e => e.UpdatedAt)
                    .HasDefaultValueSql("NOW()")
                    .HasConversion(
                        v => v.Kind == DateTimeKind.Unspecified ? DateTime.SpecifyKind(v, DateTimeKind.Utc) : v.ToUniversalTime(),
                        v => DateTime.SpecifyKind(v, DateTimeKind.Utc));
                entity.Property(e => e.BirthDate)
                    .HasConversion(
                        v => v.HasValue 
                            ? (v.Value.Kind == DateTimeKind.Unspecified 
                                ? DateTime.SpecifyKind(v.Value, DateTimeKind.Utc) 
                                : v.Value.ToUniversalTime())
                            : (DateTime?)null,
                        v => v.HasValue ? DateTime.SpecifyKind(v.Value, DateTimeKind.Utc) : (DateTime?)null);
                
                // ENUM mappings - Convert to string (no PostgreSQL enum types)
                entity.Property(e => e.Role)
                    .HasConversion<string>()
                    .HasMaxLength(50);

                entity.Property(e => e.Gender)
                    .HasConversion<string>()
                    .HasMaxLength(20);

                
                // Indexes
                entity.HasIndex(e => e.NationalCode);
                
                // Relationships
                entity.HasOne(u => u.ProviderProfile)
                    .WithOne(p => p.User)
                    .HasForeignKey<ProviderProfile>(p => p.UserId)
                    .OnDelete(DeleteBehavior.Cascade);
                    
                entity.HasOne(u => u.PatientProfile)
                    .WithOne(p => p.User)
                    .HasForeignKey<PatientProfile>(p => p.UserId)
                    .OnDelete(DeleteBehavior.Cascade);
            });

            // SpecialtyCategory Configuration
            modelBuilder.Entity<SpecialtyCategory>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Name).HasMaxLength(100);
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
                entity.HasMany(e => e.Specialties)
                    .WithOne(s => s.Category)
                    .HasForeignKey(s => s.CategoryId)
                    .OnDelete(DeleteBehavior.SetNull);
            });

            // Specialty Configuration
            modelBuilder.Entity<Specialty>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Name).HasMaxLength(100);
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
            });

            // ProviderProfile Configuration
            modelBuilder.Entity<ProviderProfile>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Degree).HasMaxLength(50);
                entity.Property(e => e.SharePercent).HasColumnType("NUMERIC(5,2)");
                entity.Property(e => e.IsActive).HasDefaultValue(true);
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
                
                entity.HasOne(p => p.User)
                    .WithOne(u => u.ProviderProfile)
                    .HasForeignKey<ProviderProfile>(p => p.UserId)
                    .OnDelete(DeleteBehavior.Cascade);
                    
                entity.HasOne(p => p.Clinic)
                    .WithMany()
                    .HasForeignKey(p => p.ClinicId)
                    .OnDelete(DeleteBehavior.SetNull);
                    
                entity.HasOne(p => p.Specialty)
                    .WithMany()
                    .HasForeignKey(p => p.SpecialtyId)
                    .OnDelete(DeleteBehavior.SetNull);
                    
                entity.HasMany(p => p.WorkSchedules)
                    .WithOne(w => w.Provider)
                    .HasForeignKey(w => w.ProviderId)
                    .OnDelete(DeleteBehavior.Cascade);
            });

            // WorkSchedule Configuration
            modelBuilder.Entity<WorkSchedule>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.IsActive).HasDefaultValue(true);
                entity.Property(e => e.DayOfWeek)
                    .HasConversion<string>()
                    .HasMaxLength(20);
            });

            // PatientProfile Configuration
            modelBuilder.Entity<PatientProfile>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.BloodType).HasMaxLength(5);
                entity.Property(e => e.Height).HasColumnType("NUMERIC(5,2)");
                entity.Property(e => e.Weight).HasColumnType("NUMERIC(5,2)");
                entity.Property(e => e.EmergencyName).HasMaxLength(100);
                entity.Property(e => e.EmergencyRelationship).HasMaxLength(50);
                entity.Property(e => e.EmergencyPhone).HasMaxLength(20);
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
                
                entity.HasOne(p => p.User)
                    .WithOne(u => u.PatientProfile)
                    .HasForeignKey<PatientProfile>(p => p.UserId)
                    .OnDelete(DeleteBehavior.Cascade);
                    
                entity.HasMany(p => p.Insurances)
                    .WithOne(pi => pi.PatientProfile)
                    .HasForeignKey(pi => pi.PatientProfileId)
                    .OnDelete(DeleteBehavior.Cascade);
            });

            // Clinic Configuration
            modelBuilder.Entity<Clinic>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Name).HasMaxLength(150);
                entity.Property(e => e.Phone).HasMaxLength(20);
                entity.Property(e => e.Email).HasMaxLength(100);
                entity.Property(e => e.LogoUrl).HasMaxLength(255);
                entity.Property(e => e.IsActive).HasDefaultValue(true);
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
                
                entity.HasOne(c => c.Manager)
                    .WithMany()
                    .HasForeignKey(c => c.ManagerId)
                    .OnDelete(DeleteBehavior.SetNull);
                    
                entity.HasMany(c => c.WorkHours)
                    .WithOne(w => w.Clinic)
                    .HasForeignKey(w => w.ClinicId)
                    .OnDelete(DeleteBehavior.Cascade);
                    
                entity.HasMany(c => c.Addresses)
                    .WithOne(a => a.Clinic)
                    .HasForeignKey(a => a.ClinicId)
                    .OnDelete(DeleteBehavior.Cascade);
            });

            // ClinicWorkHours Configuration
            modelBuilder.Entity<ClinicWorkHours>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.IsActive).HasDefaultValue(true);
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
                entity.Property(e => e.DayOfWeek)
                    .HasConversion<string>()
                    .HasMaxLength(20);
            });

            // ClinicAddress Configuration
            modelBuilder.Entity<ClinicAddress>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Street).HasMaxLength(150);
                entity.Property(e => e.City).HasMaxLength(100);
                entity.Property(e => e.State).HasMaxLength(100);
                entity.Property(e => e.PostalCode).HasMaxLength(20);
                entity.Property(e => e.Country).HasMaxLength(50);
            });

            // ServiceCategory Configuration
            modelBuilder.Entity<ServiceCategory>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Name).HasMaxLength(100);
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
                entity.HasMany(e => e.Services)
                    .WithOne(s => s.Category)
                    .HasForeignKey(s => s.CategoryId)
                    .OnDelete(DeleteBehavior.SetNull);
            });

            // Service Configuration
            modelBuilder.Entity<Service>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Name).HasMaxLength(150);
                entity.Property(e => e.BasePrice).HasColumnType("NUMERIC(10,2)");
                entity.Property(e => e.IsInPerson).HasDefaultValue(true);
                entity.Property(e => e.RequiresDoctor).HasDefaultValue(false);
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
            });

            // Insurance Configuration
            modelBuilder.Entity<Insurance>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Name).HasMaxLength(100);
                entity.Property(e => e.CoveragePercent).HasColumnType("NUMERIC(5,2)");
                entity.Property(e => e.IsActive).HasDefaultValue(true);
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
            });

            // PatientInsurance Configuration
            modelBuilder.Entity<PatientInsurance>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.InsuranceNumber).HasMaxLength(50);
                entity.Property(e => e.IsActive).HasDefaultValue(true);
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
            });

            // ClinicInsurance Configuration
            modelBuilder.Entity<ClinicInsurance>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
            });

            // ClinicService Configuration
            modelBuilder.Entity<ClinicService>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Price).HasColumnType("NUMERIC(10,2)");
                entity.Property(e => e.Active).HasDefaultValue(true);
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
            });

            // ServiceRequest Configuration
            modelBuilder.Entity<ServiceRequest>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.TotalPrice).HasColumnType("NUMERIC(10,2)");
                entity.Property(e => e.InsuranceCovered).HasColumnType("NUMERIC(10,2)");
                entity.Property(e => e.PatientPayable).HasColumnType("NUMERIC(10,2)");
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
                entity.Property(e => e.UpdatedAt).HasDefaultValueSql("NOW()");
                entity.Property(e => e.Status)
                    .HasConversion<string>()
                    .HasMaxLength(50);

                entity.Property(e => e.AppointmentType)
                    .HasConversion<string>()
                    .HasMaxLength(50);
                
                entity.HasOne(sr => sr.Patient)
                    .WithMany(u => u.ServiceRequests)
                    .HasForeignKey(sr => sr.PatientId)
                    .OnDelete(DeleteBehavior.Cascade);
                    
                entity.HasOne(sr => sr.Clinic)
                    .WithMany()
                    .HasForeignKey(sr => sr.ClinicId)
                    .OnDelete(DeleteBehavior.SetNull);
                    
                entity.HasOne(sr => sr.Service)
                    .WithMany()
                    .HasForeignKey(sr => sr.ServiceId)
                    .OnDelete(DeleteBehavior.SetNull);
                    
                entity.HasOne(sr => sr.Insurance)
                    .WithMany()
                    .HasForeignKey(sr => sr.InsuranceId)
                    .OnDelete(DeleteBehavior.SetNull);
                    
                entity.HasOne(sr => sr.PerformedByUser)
                    .WithMany()
                    .HasForeignKey(sr => sr.PerformedByUserId)
                    .OnDelete(DeleteBehavior.SetNull);
                    
                entity.HasMany(sr => sr.ServiceResults)
                    .WithOne(sr => sr.Request)
                    .HasForeignKey(sr => sr.RequestId)
                    .OnDelete(DeleteBehavior.Cascade);
                    
                entity.HasMany(sr => sr.Payments)
                    .WithOne(p => p.Request)
                    .HasForeignKey(p => p.RequestId)
                    .OnDelete(DeleteBehavior.Cascade);
                
                // Indexes
                entity.HasIndex(e => e.PatientId);
                entity.HasIndex(e => e.Status);
            });

            // ServiceResult Configuration
            modelBuilder.Entity<ServiceResult>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.AttachmentUrl).HasMaxLength(255);
                entity.Property(e => e.ApprovedByAdmin).HasDefaultValue(false);
            });

            // Payment Configuration
            modelBuilder.Entity<Payment>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Amount).HasColumnType("NUMERIC(10,2)");
                entity.Property(e => e.TransactionId).HasMaxLength(100);
                entity.Property(e => e.Method)
                    .HasConversion<string>()
                    .HasMaxLength(50);

                entity.Property(e => e.Status)
                    .HasConversion<string>()
                    .HasMaxLength(50);
            });

            // Notification Configuration
            modelBuilder.Entity<Notification>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Title).HasMaxLength(150);
                entity.Property(e => e.IsRead).HasDefaultValue(false);
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
                entity.Property(e => e.Type)
                    .HasConversion<string>()
                    .HasMaxLength(50);
                    
                entity.HasIndex(e => e.UserId);
                entity.HasIndex(e => e.IsRead);
            });

            // AuditLog Configuration
            modelBuilder.Entity<AuditLog>(entity =>
            {
                entity.HasKey(e => e.Id);
                entity.Property(e => e.Id).ValueGeneratedOnAdd();
                entity.Property(e => e.Action).HasMaxLength(100);
                entity.Property(e => e.Entity).HasMaxLength(50);
                entity.Property(e => e.CreatedAt).HasDefaultValueSql("NOW()");
                
                entity.HasIndex(e => e.UserId);
            });

        }
    }
}
