CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "OtpVerifications" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Phone" character varying(20) NOT NULL,
    "Code" character varying(10) NOT NULL,
    "ExpiresAt" timestamp with time zone NOT NULL,
    "IsUsed" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    CONSTRAINT "PK_OtpVerifications" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_OtpVerifications_CreatedAt" ON "OtpVerifications" ("CreatedAt");

CREATE INDEX "IX_OtpVerifications_Phone_Code" ON "OtpVerifications" ("Phone", "Code");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20251126075404_AddOtpVerification', '8.0.11');

COMMIT;

