CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "Insurances" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100),
        "Description" text,
        "CoveragePercent" numeric(5,2),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_Insurances" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "ServiceCategories" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100),
        "Description" text,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_ServiceCategories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "SpecialtyCategories" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(100),
        "Description" text,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_SpecialtyCategories" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "User" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "FirstName" character varying(255) NOT NULL,
        "LastName" character varying(255) NOT NULL,
        "NationalCode" character varying(10) NOT NULL,
        "Phone" character varying(20) NOT NULL,
        "Email" character varying(100) NOT NULL,
        "PasswordHash" character varying(255) NOT NULL,
        "Role" character varying(50) NOT NULL,
        "Gender" character varying(20),
        "BirthDate" timestamp with time zone,
        "AvatarUrl" character varying(255),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "DeletedAt" timestamp with time zone,
        CONSTRAINT "PK_User" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "Services" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(150),
        "Description" text,
        "CategoryId" bigint,
        "BasePrice" numeric(10,2),
        "DurationMinutes" integer,
        "IsInPerson" boolean NOT NULL DEFAULT TRUE,
        "RequiresDoctor" boolean NOT NULL DEFAULT FALSE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_Services" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Services_ServiceCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "ServiceCategories" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "Specialties" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "CategoryId" bigint,
        "Name" character varying(100),
        "Description" text,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_Specialties" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Specialties_SpecialtyCategories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "SpecialtyCategories" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "AuditLogs" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" bigint,
        "Action" character varying(100),
        "Entity" character varying(50),
        "EntityId" bigint,
        "OldValue" text,
        "NewValue" text,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AuditLogs_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "Clinics" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Name" character varying(150),
        "Phone" character varying(20),
        "Email" character varying(100),
        "ManagerId" bigint,
        "LogoUrl" character varying(255),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_Clinics" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Clinics_User_ManagerId" FOREIGN KEY ("ManagerId") REFERENCES "User" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "Notifications" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" bigint NOT NULL,
        "Title" character varying(150),
        "Message" text,
        "Type" character varying(50) NOT NULL,
        "IsRead" boolean NOT NULL DEFAULT FALSE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_Notifications" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Notifications_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "PatientProfiles" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" bigint NOT NULL,
        "BloodType" character varying(5),
        "Height" numeric(5,2),
        "Weight" numeric(5,2),
        "MedicalHistory" text,
        "EmergencyName" character varying(100),
        "EmergencyRelationship" character varying(50),
        "EmergencyPhone" character varying(20),
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_PatientProfiles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PatientProfiles_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "ClinicAddresses" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ClinicId" bigint NOT NULL,
        "Street" character varying(150),
        "City" character varying(100),
        "State" character varying(100),
        "PostalCode" character varying(20),
        "Country" character varying(50),
        CONSTRAINT "PK_ClinicAddresses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ClinicAddresses_Clinics_ClinicId" FOREIGN KEY ("ClinicId") REFERENCES "Clinics" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "ClinicInsurances" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ClinicId" bigint NOT NULL,
        "InsuranceId" bigint NOT NULL,
        CONSTRAINT "PK_ClinicInsurances" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ClinicInsurances_Clinics_ClinicId" FOREIGN KEY ("ClinicId") REFERENCES "Clinics" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ClinicInsurances_Insurances_InsuranceId" FOREIGN KEY ("InsuranceId") REFERENCES "Insurances" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "ClinicServices" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ClinicId" bigint NOT NULL,
        "ServiceId" bigint NOT NULL,
        "Price" numeric(10,2),
        "Active" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_ClinicServices" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ClinicServices_Clinics_ClinicId" FOREIGN KEY ("ClinicId") REFERENCES "Clinics" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ClinicServices_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "ClinicWorkHours" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ClinicId" bigint NOT NULL,
        "DayOfWeek" character varying(20) NOT NULL,
        "StartTime" interval,
        "EndTime" interval,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_ClinicWorkHours" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ClinicWorkHours_Clinics_ClinicId" FOREIGN KEY ("ClinicId") REFERENCES "Clinics" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "ProviderProfiles" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "UserId" bigint NOT NULL,
        "ClinicId" bigint,
        "SpecialtyId" bigint,
        "Degree" character varying(50),
        "ExperienceYears" integer,
        "SharePercent" numeric(5,2),
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_ProviderProfiles" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ProviderProfiles_Clinics_ClinicId" FOREIGN KEY ("ClinicId") REFERENCES "Clinics" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_ProviderProfiles_Specialties_SpecialtyId" FOREIGN KEY ("SpecialtyId") REFERENCES "Specialties" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_ProviderProfiles_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "ServiceRequests" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PatientId" bigint NOT NULL,
        "ClinicId" bigint,
        "ServiceId" bigint,
        "InsuranceId" bigint,
        "PerformedByUserId" bigint,
        "PreferredTime" timestamp with time zone,
        "AppointmentType" character varying(50),
        "Status" character varying(50) NOT NULL,
        "TotalPrice" numeric(10,2),
        "InsuranceCovered" numeric(10,2),
        "PatientPayable" numeric(10,2),
        "Notes" text,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        "UpdatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_ServiceRequests" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ServiceRequests_Clinics_ClinicId" FOREIGN KEY ("ClinicId") REFERENCES "Clinics" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_ServiceRequests_Insurances_InsuranceId" FOREIGN KEY ("InsuranceId") REFERENCES "Insurances" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_ServiceRequests_Services_ServiceId" FOREIGN KEY ("ServiceId") REFERENCES "Services" ("Id") ON DELETE SET NULL,
        CONSTRAINT "FK_ServiceRequests_User_PatientId" FOREIGN KEY ("PatientId") REFERENCES "User" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ServiceRequests_User_PerformedByUserId" FOREIGN KEY ("PerformedByUserId") REFERENCES "User" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "PatientInsurances" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "PatientProfileId" bigint NOT NULL,
        "InsuranceId" bigint NOT NULL,
        "InsuranceNumber" character varying(50),
        "ValidFrom" timestamp with time zone,
        "ValidTo" timestamp with time zone,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
        CONSTRAINT "PK_PatientInsurances" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PatientInsurances_Insurances_InsuranceId" FOREIGN KEY ("InsuranceId") REFERENCES "Insurances" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PatientInsurances_PatientProfiles_PatientProfileId" FOREIGN KEY ("PatientProfileId") REFERENCES "PatientProfiles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "WorkSchedules" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "ProviderId" bigint NOT NULL,
        "DayOfWeek" character varying(20) NOT NULL,
        "StartTime" interval,
        "EndTime" interval,
        "IsActive" boolean NOT NULL DEFAULT TRUE,
        CONSTRAINT "PK_WorkSchedules" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_WorkSchedules_ProviderProfiles_ProviderId" FOREIGN KEY ("ProviderId") REFERENCES "ProviderProfiles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "Payments" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RequestId" bigint NOT NULL,
        "Amount" numeric(10,2),
        "Method" character varying(50),
        "TransactionId" character varying(100),
        "Status" character varying(50) NOT NULL,
        "PaidAt" timestamp with time zone,
        CONSTRAINT "PK_Payments" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Payments_ServiceRequests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "ServiceRequests" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE TABLE "ServiceResults" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "RequestId" bigint NOT NULL,
        "PerformedByUserId" bigint,
        "ResultText" text,
        "AttachmentUrl" character varying(255),
        "SubmittedAt" timestamp with time zone,
        "ApprovedByAdmin" boolean NOT NULL DEFAULT FALSE,
        CONSTRAINT "PK_ServiceResults" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ServiceResults_ServiceRequests_RequestId" FOREIGN KEY ("RequestId") REFERENCES "ServiceRequests" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_ServiceResults_User_PerformedByUserId" FOREIGN KEY ("PerformedByUserId") REFERENCES "User" ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_AuditLogs_UserId" ON "AuditLogs" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ClinicAddresses_ClinicId" ON "ClinicAddresses" ("ClinicId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ClinicInsurances_ClinicId" ON "ClinicInsurances" ("ClinicId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ClinicInsurances_InsuranceId" ON "ClinicInsurances" ("InsuranceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_Clinics_ManagerId" ON "Clinics" ("ManagerId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ClinicServices_ClinicId" ON "ClinicServices" ("ClinicId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ClinicServices_ServiceId" ON "ClinicServices" ("ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ClinicWorkHours_ClinicId" ON "ClinicWorkHours" ("ClinicId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_Notifications_IsRead" ON "Notifications" ("IsRead");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_Notifications_UserId" ON "Notifications" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_PatientInsurances_InsuranceId" ON "PatientInsurances" ("InsuranceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_PatientInsurances_PatientProfileId" ON "PatientInsurances" ("PatientProfileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_PatientProfiles_UserId" ON "PatientProfiles" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_Payments_RequestId" ON "Payments" ("RequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ProviderProfiles_ClinicId" ON "ProviderProfiles" ("ClinicId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ProviderProfiles_SpecialtyId" ON "ProviderProfiles" ("SpecialtyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_ProviderProfiles_UserId" ON "ProviderProfiles" ("UserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ServiceRequests_ClinicId" ON "ServiceRequests" ("ClinicId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ServiceRequests_InsuranceId" ON "ServiceRequests" ("InsuranceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ServiceRequests_PatientId" ON "ServiceRequests" ("PatientId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ServiceRequests_PerformedByUserId" ON "ServiceRequests" ("PerformedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ServiceRequests_ServiceId" ON "ServiceRequests" ("ServiceId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ServiceRequests_Status" ON "ServiceRequests" ("Status");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ServiceResults_PerformedByUserId" ON "ServiceResults" ("PerformedByUserId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_ServiceResults_RequestId" ON "ServiceResults" ("RequestId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_Services_CategoryId" ON "Services" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_Specialties_CategoryId" ON "Specialties" ("CategoryId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_User_Email" ON "User" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_User_NationalCode" ON "User" ("NationalCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    CREATE INDEX "IX_WorkSchedules_ProviderId" ON "WorkSchedules" ("ProviderId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131029_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251129131029_InitialCreate', '8.0.11');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251129131042_AddOtpVerification') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251129131042_AddOtpVerification', '8.0.11');
    END IF;
END $EF$;
COMMIT;

